name: lungconvt
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.9
  
  # Core scientific packages
  - numpy=1.23.*
  - pandas=1.5.*
  - matplotlib=3.6.*
  - seaborn=0.12.*
  - scikit-learn=1.2.*
  
  # Image processing
  - pillow=9.4.*
  # Note: opencv installed via pip for headless version
  
  # Deep learning
  - cudatoolkit=11.8  # Adjust based on your CUDA version
  - cudnn=8.6.*
  
  # Utilities
  - pyyaml=6.0
  - h5py=3.8.*
  - tqdm=4.65.*
  - psutil=5.9.*
  
  # Jupyter
  - jupyter=1.0.*
  - notebook=6.5.*
  - ipywidgets=8.0.*
  
  # Visualization
  - plotly=5.13.*
  
  # Development tools
  - black=23.1.*
  - flake8=6.0.*
  - pytest=7.2.*
  - pytest-cov=4.0.*
  
  # Pip dependencies
  - pip
  - pip:
    # TensorFlow must be installed via pip for GPU support
    - tensorflow==2.12.0
    - tensorflow-addons==0.20.0
    - opencv-python-headless>=4.5.0